name: unitunes
description: "Music link converter between Spotify, YouTube Music, and Tidal"
publish_to: 'none'

version: 0.2.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  receive_sharing_intent: ^1.8.1
  http: ^1.2.0
  spotify: ^0.13.4
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
